mappings:
  - destination:
      category: AccessSubject
      datatype: string
      id: user.role
    dictionary:
      martin: manager
      cecilia: consultant
    source:
      category: AccessSubject
      datatype: string
      id: user.identity
  - destination:
      category: AccessSubject
      datatype: string
      id: user.location
    dictionary:
      martin: stockholm
      cecilia: london
    source:
      category: AccessSubject
      datatype: string
      id: user.identity
  - destination:
      category: Resource
      datatype: string
      id: resource.location
    dictionary:
      2: stockholm
      1: london
    source:
      category: Resource
      datatype: string
      id: resource.identity